# Generated by Django 4.2.20 on 2025-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comparision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=252, null=True)),
                ('currency', models.CharField(max_length=252, null=True)),
                ('country', models.CharField(max_length=252, null=True)),
                ('coin_rupee_value', models.CharField(max_length=252, null=True)),
                ('coin_year', models.DateTimeField(max_length=252, null=True)),
                ('coin_mint_marks', models.CharField(max_length=252, null=True)),
                ('coin_mint_marks_city', models.CharField(max_length=252, null=True)),
                ('color', models.CharField(max_length=252, null=True)),
                ('shape', models.CharField(max_length=252, null=True)),
                ('which_metal_body', models.CharField(max_length=252, null=True)),
                ('coin_symbol', models.CharField(max_length=252, null=True)),
                ('reverse_symbol', models.CharField(max_length=252, null=True)),
                ('weight', models.IntegerField(max_length=50, null=True)),
                ('size', models.IntegerField(max_length=50, null=True)),
            ],
        ),
    ]
