# Generated by Django 4.2.20 on 2025-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comparision',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
