# Generated by Django 4.2.20 on 2025-04-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compar', '0002_alter_comparision_size_alter_comparision_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparision',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
