# Generated by Django 4.2.20 on 2025-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compar', '0003_comparision_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='coin_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
