# Generated by Django 4.2.20 on 2025-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compar', '0004_alter_comparision_coin_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparision',
            name='weight',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
