# Generated by Django 4.2.20 on 2025-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compar', '0006_alter_comparision_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparision',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
